CREATE TABLE IF NOT EXISTS users(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL, 
    password VARCHAR(255) NOT NULL,
    role enum ('admin', 'user') NOT NULL DEFAULT 'user'
);
