CREATE TABLE IF NOT EXISTS students(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    age INT(3) NOT NULL,
    email VARCHAR(50) 
);
